# Generated by Django 5.2 on 2025-04-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='special_images/'),
        ),
    ]
