# Generated by Django 3.2 on 2025-04-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_offer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
    ]
