# Generated by Django 5.2 on 2025-04-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_admin_store_alter_menu_admin_alter_menu_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='category_name',
        ),
    ]
