# Generated by Django 5.2 on 2025-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_remove_menucategory_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='discount',
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
